
name: Python Package Release

on:
  release:
    types: [published]
    branches: 
      - master
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[complete]
    - name: Release
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        TWINE_USER: '__token__'
      run: |
        inv release.new


